import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav-bar";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body className={`${inter.className} scroll bg-background text-text `}>
        <div className="grid auto-rows-[auto_1fr_auto] ">
          <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
